function [fitresult, gof] = myGaussianFit2(myX, myY)
%CREATEFIT(MYX,MYY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : myX
%      Y Output: myY
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Jan-2019 18:51:22


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( myX, myY );

% Set up fittype and options.
ft = fittype( 'a*exp(-((x-b)/c)^2) + d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.DiffMaxChange = 1;
opts.DiffMinChange = 0.001;
opts.Display = 'Off';
opts.Lower = [0 1 -Inf -100];
opts.MaxFunEvals = 1000;
opts.MaxIter = 1000;
opts.StartPoint = [15 1.53 1 -65];
opts.Upper = [100 2 Inf 0];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'myY vs. myX', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel myX
ylabel myY
grid on


