function [fitresult, gof] = myLinearFit(spins, pics)
%CREATEFIT(SPINS,PICS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : spins
%      Y Output: pics
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Feb-2019 10:11:59


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( spins, pics );

% Set up fittype and options.
ft = fittype( 'a*x+b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.677119483753799 0.898330525448193];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'NO untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'data', 'linear fit', 'Location', 'NorthEast' );
% Label axes
xlabel("elongation [strain]");
ylabel("pics wavelength [um]");
grid on


