function [fitresult, gof] = splineFit(xAxis, spectral_shift)
%CREATEFIT(XAXIS,SPECTRAL_SHIFT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xAxis
%      Y Output: spectral_shift
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Mar-2019 23:14:52


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xAxis, spectral_shift );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.99999999;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'spectral_shift vs. xAxis', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel xAxis
ylabel spectral_shift
grid on


